global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['backend_grupo8:3000']

  - job_name: 'backend-deploy'
    scrape_interval: 5s
    static_configs:
      - targets: ['pdesa-backend-adriancardozo.azurewebsites.net']
