const zapatilla = require('../product/zapatilla.js');

module.exports = {
  id: 'zapatillas',
  keywords: 'zapatillas',
  paging: {
    total: 10,
    limit: 10,
    offset: 0,
  },
  results: [
    zapatilla,
    {
      id: 'MLA44034532',
      name: 'Zapatillas Response Ih6096 adidas',
      description: '',
      date_created: '2024-11-28T15:03:05Z',
      keywords: 'Zapatillas Response Ih6096 adidas',
      attributes: [
        {
          id: 'BRAND',
          name: 'Marca',
          value_id: '14810',
          value_name: 'adidas',
        },
        {
          id: 'LINE',
          name: 'Línea',
          value_id: '13363121',
          value_name: 'Running',
        },
        {
          id: 'MODEL',
          name: 'Modelo',
          value_id: '472835',
          value_name: 'Response',
        },
        {
          id: 'GENDER',
          name: 'Género',
          value_id: '339666',
          value_name: 'Hombre',
        },
        {
          id: 'ALPHANUMERIC_MODEL',
          name: 'Modelo alfanumérico',
          value_id: '46928594',
          value_name: 'IH6008',
        },
        {
          id: 'COLOR',
          name: 'Color',
          value_id: '283165',
          value_name: 'Gris',
        },
        {
          id: 'FABRIC_DESIGN',
          name: 'Diseño de la tela',
          value_id: '24721100',
          value_name: 'Liso',
        },
        {
          id: 'WIDTH_TYPE',
          name: 'Tipo de ancho',
          value_id: '44710799',
          value_name: 'Ajuste clásico',
        },
        {
          id: 'SIZE_GRID_ROW_ID',
          name: 'ID de la fila de la guía de talles',
          value_id: '45134210',
          value_name: '2516266:10',
        },
        {
          id: 'SIZE_GRID_ID',
          name: 'ID de la guía de talles',
          value_id: '45028923',
          value_name: '2516266',
        },
        {
          id: 'EXTERIOR_MATERIALS',
          name: 'Materiales del exterior',
          value_name: 'Textil',
        },
        {
          id: 'INTERIOR_MATERIALS',
          name: 'Materiales del interior',
          value_name: 'Textil',
        },
        {
          id: 'OUTSOLE_MATERIALS',
          name: 'Materiales de la suela',
          value_name: 'Sintético',
        },
        {
          id: 'FOOTWEAR_TYPE',
          name: 'Tipo de calzado',
          value_id: '517583',
          value_name: 'Zapatilla',
        },
        {
          id: 'ADJUSTMENT_TYPES',
          name: 'Tipos de ajuste',
          value_name: 'Cordones',
        },
        {
          id: 'WITH_RECYCLED_MATERIALS',
          name: 'Con materiales reciclados',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'RECOMMENDED_USES',
          name: 'Usos recomendados',
          value_name: 'Deportivo, Running',
        },
        {
          id: 'IS_IMPERMEABLE',
          name: 'Es impermeable',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_ANTI_SLIP_OUTSOLE',
          name: 'Con suela antideslizante',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PLATFORM',
          name: 'Con plataforma',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_REMOVABLE_INSOLES',
          name: 'Con plantillas removibles',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_BREATHEABLE_INSOLES',
          name: 'Con plantillas transpirables',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'INSOLES_MATERIALS',
          name: 'Materiales de las plantillas',
          value_name: 'Espuma',
        },
        {
          id: 'SHAFT_TYPE',
          name: 'Tipo de caña',
          value_id: '1164226',
          value_name: 'Baja',
        },
        {
          id: 'MIDSOLE_MATERIALS',
          name: 'Materiales de la mediasuela',
          value_name: 'Espuma',
        },
        {
          id: 'WITH_PADDED_MIDSOLE',
          name: 'Con mediasuela acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_TONGUE',
          name: 'Con lengüeta acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_COLLAR',
          name: 'Con cuello acolchado',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'SUITABLE_SURFACES',
          name: 'Superficies aptas',
          value_name: 'Cemento',
        },
        {
          id: 'RELEASE_SEASON',
          name: 'Temporada de lanzamiento',
          value_id: '994284',
          value_name: 'Otoño/Invierno',
        },
        {
          id: 'RELEASE_YEAR',
          name: 'Año de lanzamiento',
          value_id: '11166326',
          value_name: '2022',
        },
        {
          id: 'SIZE',
          name: 'Talle',
          value_name: '39.5 AR',
        },
      ],
      pictures: [
        {
          id: '648930-MLA80994410011_112024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_648930-MLA80994410011_112024-F.jpg',
        },
        {
          id: '998833-MLA80994342287_112024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_998833-MLA80994342287_112024-F.jpg',
        },
        {
          id: '845580-MLA80994410019_112024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_845580-MLA80994410019_112024-F.jpg',
        },
        {
          id: '723462-MLA80994371971_112024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_723462-MLA80994371971_112024-F.jpg',
        },
        {
          id: '911378-MLA80994410035_112024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_911378-MLA80994410035_112024-F.jpg',
        },
        {
          id: '955875-MLA80994342323_112024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_955875-MLA80994342323_112024-F.jpg',
        },
        {
          id: '857442-MLA80994313335_112024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_857442-MLA80994313335_112024-F.jpg',
        },
      ],
      status: 'active',
      catalog_product_id: 'MLA44034532',
      pdp_types: [],
      domain_id: 'MLA-SNEAKERS',
      settings: {
        listing_strategy: 'open',
        exclusive: false,
      },
      main_features: [],
      children_ids: [],
      quality_type: 'COMPLETE',
      priority: 'MEDIUM',
      type: 'PRODUCT',
      site_id: 'MLA',
      variations: [],
      parent_id: 'MLA43943343',
    },
    {
      id: 'MLA44732049',
      name: 'Zapatillas Aspyre Ji2121 adidas',
      description: '',
      date_created: '2024-12-12T20:14:27Z',
      keywords: 'Zapatillas Aspyre Ji2121 adidas',
      attributes: [
        {
          id: 'BRAND',
          name: 'Marca',
          value_id: '14810',
          value_name: 'adidas',
        },
        {
          id: 'MODEL',
          name: 'Modelo',
          value_id: '45655200',
          value_name: 'Aspyre',
        },
        {
          id: 'GENDER',
          name: 'Género',
          value_id: '339666',
          value_name: 'Hombre',
        },
        {
          id: 'COLOR',
          name: 'Color',
          value_id: '52055',
          value_name: 'Blanco',
        },
        {
          id: 'FABRIC_DESIGN',
          name: 'Diseño de la tela',
          value_id: '24721100',
          value_name: 'Liso',
        },
        {
          id: 'WIDTH_TYPE',
          name: 'Tipo de ancho',
          value_id: '44710799',
          value_name: 'Ajuste clásico',
        },
        {
          id: 'SIZE_GRID_ROW_ID',
          name: 'ID de la fila de la guía de talles',
          value_id: '45665840',
          value_name: '2632349:5',
        },
        {
          id: 'MAIN_COLOR',
          name: 'Color principal',
          value_id: '2450308',
          value_name: 'Blanco',
        },
        {
          id: 'SIZE_GRID_ID',
          name: 'ID de la guía de talles',
          value_id: '45655234',
          value_name: '2632349',
        },
        {
          id: 'EXTERIOR_MATERIALS',
          name: 'Materiales del exterior',
          value_name: 'Tela',
        },
        {
          id: 'INTERIOR_MATERIALS',
          name: 'Materiales del interior',
          value_name: 'Tela',
        },
        {
          id: 'OUTSOLE_MATERIALS',
          name: 'Materiales de la suela',
          value_name: 'Sintético',
        },
        {
          id: 'FOOTWEAR_TYPE',
          name: 'Tipo de calzado',
          value_id: '517583',
          value_name: 'Zapatilla',
        },
        {
          id: 'ADJUSTMENT_TYPES',
          name: 'Tipos de ajuste',
          value_name: 'Cordones',
        },
        {
          id: 'WITH_RECYCLED_MATERIALS',
          name: 'Con materiales reciclados',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'RECOMMENDED_USES',
          name: 'Usos recomendados',
          value_name: 'Lifestyle',
        },
        {
          id: 'IS_IMPERMEABLE',
          name: 'Es impermeable',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_ANTI_SLIP_OUTSOLE',
          name: 'Con suela antideslizante',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PLATFORM',
          name: 'Con plataforma',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'SHAFT_TYPE',
          name: 'Tipo de caña',
          value_id: '1164226',
          value_name: 'Baja',
        },
        {
          id: 'MIDSOLE_MATERIALS',
          name: 'Materiales de la mediasuela',
          value_name: 'Goma EVA',
        },
        {
          id: 'WITH_PADDED_MIDSOLE',
          name: 'Con mediasuela acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_TONGUE',
          name: 'Con lengüeta acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_COLLAR',
          name: 'Con cuello acolchado',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'SUITABLE_SURFACES',
          name: 'Superficies aptas',
          value_name: 'Cemento',
        },
        {
          id: 'RELEASE_SEASON',
          name: 'Temporada de lanzamiento',
          value_id: '994284',
          value_name: 'Otoño/Invierno',
        },
        {
          id: 'RELEASE_YEAR',
          name: 'Año de lanzamiento',
          value_id: '22764580',
          value_name: '2024',
        },
        {
          id: 'SIZE',
          name: 'Talle',
          value_name: '37.5 AR',
        },
      ],
      pictures: [
        {
          id: '753562-MLA83366392406_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_753562-MLA83366392406_042025-F.jpg',
        },
        {
          id: '825243-MLA83188221046_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_825243-MLA83188221046_042025-F.jpg',
        },
        {
          id: '956234-MLA83188425122_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_956234-MLA83188425122_042025-F.jpg',
        },
        {
          id: '772729-MLA83479262327_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_772729-MLA83479262327_042025-F.jpg',
        },
        {
          id: '762953-MLA83188425126_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_762953-MLA83188425126_042025-F.jpg',
        },
        {
          id: '730855-MLA83188425128_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_730855-MLA83188425128_042025-F.jpg',
        },
        {
          id: '934201-MLA83479387735_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_934201-MLA83479387735_042025-F.jpg',
        },
        {
          id: '980378-MLA83479387741_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_980378-MLA83479387741_042025-F.jpg',
        },
        {
          id: '681541-MLA83188425136_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_681541-MLA83188425136_042025-F.jpg',
        },
      ],
      status: 'active',
      catalog_product_id: 'MLA44732049',
      pdp_types: [],
      domain_id: 'MLA-SNEAKERS',
      settings: {
        listing_strategy: 'open',
        exclusive: false,
      },
      main_features: [],
      children_ids: [],
      quality_type: 'COMPLETE',
      priority: 'MEDIUM',
      type: 'PRODUCT',
      site_id: 'MLA',
      variations: [],
      parent_id: 'MLA44526922',
    },
    {
      id: 'MLA45582927',
      name: 'Zapatillas Response Ih6092 adidas',
      description: '',
      date_created: '2025-01-18T19:52:47Z',
      keywords: 'Zapatillas Response Ih6092 adidas',
      attributes: [
        {
          id: 'BRAND',
          name: 'Marca',
          value_id: '14810',
          value_name: 'adidas',
        },
        {
          id: 'MODEL',
          name: 'Modelo',
          value_id: '472835',
          value_name: 'Response',
        },
        {
          id: 'GENDER',
          name: 'Género',
          value_id: '339666',
          value_name: 'Hombre',
        },
        {
          id: 'COLOR',
          name: 'Color',
          value_id: '283160',
          value_name: 'Turquesa',
        },
        {
          id: 'FABRIC_DESIGN',
          name: 'Diseño de la tela',
          value_id: '24721100',
          value_name: 'Liso',
        },
        {
          id: 'WIDTH_TYPE',
          name: 'Tipo de ancho',
          value_id: '44710799',
          value_name: 'Ajuste clásico',
        },
        {
          id: 'SIZE_GRID_ROW_ID',
          name: 'ID de la fila de la guía de talles',
          value_id: '45134229',
          value_name: '2516266:25',
        },
        {
          id: 'MAIN_COLOR',
          name: 'Color principal',
          value_id: '2450320',
          value_name: 'Turquesa',
        },
        {
          id: 'SIZE_GRID_ID',
          name: 'ID de la guía de talles',
          value_id: '45028923',
          value_name: '2516266',
        },
        {
          id: 'EXTERIOR_MATERIALS',
          name: 'Materiales del exterior',
          value_name: 'Tela',
        },
        {
          id: 'INTERIOR_MATERIALS',
          name: 'Materiales del interior',
          value_name: 'Tela',
        },
        {
          id: 'OUTSOLE_MATERIALS',
          name: 'Materiales de la suela',
          value_name: 'Sintético',
        },
        {
          id: 'FOOTWEAR_TYPE',
          name: 'Tipo de calzado',
          value_id: '517583',
          value_name: 'Zapatilla',
        },
        {
          id: 'ADJUSTMENT_TYPES',
          name: 'Tipos de ajuste',
          value_name: 'Cordones',
        },
        {
          id: 'WITH_RECYCLED_MATERIALS',
          name: 'Con materiales reciclados',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'RECOMMENDED_USES',
          name: 'Usos recomendados',
          value_name: 'Deportivo',
        },
        {
          id: 'IS_IMPERMEABLE',
          name: 'Es impermeable',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_ANTI_SLIP_OUTSOLE',
          name: 'Con suela antideslizante',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PLATFORM',
          name: 'Con plataforma',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_REMOVABLE_INSOLES',
          name: 'Con plantillas removibles',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_BREATHEABLE_INSOLES',
          name: 'Con plantillas transpirables',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'INSOLES_MATERIALS',
          name: 'Materiales de las plantillas',
          value_name: 'Espuma',
        },
        {
          id: 'SHAFT_TYPE',
          name: 'Tipo de caña',
          value_id: '1164226',
          value_name: 'Baja',
        },
        {
          id: 'MIDSOLE_MATERIALS',
          name: 'Materiales de la mediasuela',
          value_name: 'Goma EVA',
        },
        {
          id: 'WITH_PADDED_MIDSOLE',
          name: 'Con mediasuela acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_TONGUE',
          name: 'Con lengüeta acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_COLLAR',
          name: 'Con cuello acolchado',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'SUITABLE_SURFACES',
          name: 'Superficies aptas',
          value_name: 'Cemento',
        },
        {
          id: 'RELEASE_SEASON',
          name: 'Temporada de lanzamiento',
          value_id: '994284',
          value_name: 'Otoño/Invierno',
        },
        {
          id: 'RELEASE_YEAR',
          name: 'Año de lanzamiento',
          value_id: '22764580',
          value_name: '2024',
        },
        {
          id: 'SIZE',
          name: 'Talle',
          value_name: '49 AR',
        },
      ],
      pictures: [
        {
          id: '809003-MLA81740426454_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_809003-MLA81740426454_012025-F.jpg',
        },
        {
          id: '649600-MLA82018632145_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_649600-MLA82018632145_012025-F.jpg',
        },
        {
          id: '961345-MLA82018602925_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_961345-MLA82018602925_012025-F.jpg',
        },
        {
          id: '625834-MLA81740387956_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_625834-MLA81740387956_012025-F.jpg',
        },
        {
          id: '805954-MLA82018632147_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_805954-MLA82018632147_012025-F.jpg',
        },
        {
          id: '616134-MLA82018602931_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_616134-MLA82018602931_012025-F.jpg',
        },
        {
          id: '894065-MLA82018602935_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_894065-MLA82018602935_012025-F.jpg',
        },
        {
          id: '921990-MLA81740426470_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_921990-MLA81740426470_012025-F.jpg',
        },
        {
          id: '691861-MLA82018757247_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_691861-MLA82018757247_012025-F.jpg',
        },
      ],
      status: 'active',
      catalog_product_id: 'MLA45582927',
      pdp_types: [],
      domain_id: 'MLA-SNEAKERS',
      settings: {
        listing_strategy: 'open',
        exclusive: false,
      },
      main_features: [],
      children_ids: [],
      quality_type: 'COMPLETE',
      priority: 'MEDIUM',
      type: 'PRODUCT',
      site_id: 'MLA',
      variations: [],
      parent_id: 'MLA45582926',
    },
    {
      id: 'MLA44521354',
      name: 'Zapatillas Ultimashow Fx3640 adidas',
      description: '',
      date_created: '2024-12-05T23:11:04Z',
      keywords: 'Zapatillas Ultimashow Fx3640 adidas',
      attributes: [
        {
          id: 'BRAND',
          name: 'Marca',
          value_id: '14810',
          value_name: 'adidas',
        },
        {
          id: 'MODEL',
          name: 'Modelo',
          value_id: '11463504',
          value_name: 'Ultimashow',
        },
        {
          id: 'GENDER',
          name: 'Género',
          value_id: '339665',
          value_name: 'Mujer',
        },
        {
          id: 'COLOR',
          name: 'Color',
          value_id: '52055',
          value_name: 'Blanco',
        },
        {
          id: 'FABRIC_DESIGN',
          name: 'Diseño de la tela',
          value_id: '930483',
          value_name: 'Lisa',
        },
        {
          id: 'WIDTH_TYPE',
          name: 'Tipo de ancho',
          value_id: '44710799',
          value_name: 'Ajuste clásico',
        },
        {
          id: 'SIZE_GRID_ROW_ID',
          name: 'ID de la fila de la guía de talles',
          value_id: '45649248',
          value_name: '2549360:4',
        },
        {
          id: 'SIZE_GRID_ID',
          name: 'ID de la guía de talles',
          value_id: '45640703',
          value_name: '2549360',
        },
        {
          id: 'EXTERIOR_MATERIALS',
          name: 'Materiales del exterior',
          value_name: 'Tela',
        },
        {
          id: 'INTERIOR_MATERIALS',
          name: 'Materiales del interior',
          value_name: 'Tela',
        },
        {
          id: 'OUTSOLE_MATERIALS',
          name: 'Materiales de la suela',
          value_name: 'Sintético',
        },
        {
          id: 'FOOTWEAR_TYPE',
          name: 'Tipo de calzado',
          value_id: '517583',
          value_name: 'Zapatilla',
        },
        {
          id: 'ADJUSTMENT_TYPES',
          name: 'Tipos de ajuste',
          value_name: 'Cordones',
        },
        {
          id: 'WITH_RECYCLED_MATERIALS',
          name: 'Con materiales reciclados',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'RECOMMENDED_USES',
          name: 'Usos recomendados',
          value_name: 'Lifestyle',
        },
        {
          id: 'IS_IMPERMEABLE',
          name: 'Es impermeable',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_ANTI_SLIP_OUTSOLE',
          name: 'Con suela antideslizante',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PLATFORM',
          name: 'Con plataforma',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_LIGHTS',
          name: 'Con luces',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_REMOVABLE_INSOLES',
          name: 'Con plantillas removibles',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_BREATHEABLE_INSOLES',
          name: 'Con plantillas transpirables',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'INSOLES_MATERIALS',
          name: 'Materiales de las plantillas',
          value_name: 'Espuma',
        },
        {
          id: 'SHAFT_TYPE',
          name: 'Tipo de caña',
          value_id: '1164226',
          value_name: 'Baja',
        },
        {
          id: 'MIDSOLE_MATERIALS',
          name: 'Materiales de la mediasuela',
          value_name: 'Goma EVA',
        },
        {
          id: 'WITH_PADDED_MIDSOLE',
          name: 'Con mediasuela acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_TONGUE',
          name: 'Con lengüeta acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_COLLAR',
          name: 'Con cuello acolchado',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'SUITABLE_SURFACES',
          name: 'Superficies aptas',
          value_name: 'Asfalto',
        },
        {
          id: 'RELEASE_SEASON',
          name: 'Temporada de lanzamiento',
          value_id: '994283',
          value_name: 'Primavera/Verano',
        },
        {
          id: 'RELEASE_YEAR',
          name: 'Año de lanzamiento',
          value_id: '22764580',
          value_name: '2024',
        },
        {
          id: 'SIZE',
          name: 'Talle',
          value_name: '36 AR',
        },
      ],
      pictures: [
        {
          id: '926977-MLA81193817953_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_926977-MLA81193817953_122024-F.jpg',
        },
        {
          id: '669684-MLA80927515998_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_669684-MLA80927515998_122024-F.jpg',
        },
        {
          id: '983451-MLA80927391168_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_983451-MLA80927391168_122024-F.jpg',
        },
        {
          id: '612587-MLA81193817965_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_612587-MLA81193817965_122024-F.jpg',
        },
        {
          id: '681279-MLA81193759965_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_681279-MLA81193759965_122024-F.jpg',
        },
        {
          id: '822630-MLA81193817991_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_822630-MLA81193817991_122024-F.jpg',
        },
        {
          id: '917231-MLA80927516022_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_917231-MLA80927516022_122024-F.jpg',
        },
        {
          id: '901752-MLA81193885299_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_901752-MLA81193885299_122024-F.jpg',
        },
        {
          id: '690610-MLA81193759999_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_690610-MLA81193759999_122024-F.jpg',
        },
      ],
      status: 'active',
      catalog_product_id: 'MLA44521354',
      pdp_types: [],
      domain_id: 'MLA-SNEAKERS',
      settings: {
        listing_strategy: 'open',
        exclusive: false,
      },
      main_features: [],
      children_ids: [],
      quality_type: 'COMPLETE',
      priority: 'MEDIUM',
      type: 'PRODUCT',
      site_id: 'MLA',
      variations: [],
      parent_id: 'MLA44513695',
    },
    {
      id: 'MLA46411446',
      name: 'Zapatillas Response Ih6092 adidas',
      description: '',
      date_created: '2025-02-24T18:19:52Z',
      keywords: 'Zapatillas Response Ih6092 adidas',
      attributes: [
        {
          id: 'BRAND',
          name: 'Marca',
          value_id: '14810',
          value_name: 'adidas',
        },
        {
          id: 'MODEL',
          name: 'Modelo',
          value_id: '472835',
          value_name: 'Response',
        },
        {
          id: 'GENDER',
          name: 'Género',
          value_id: '339666',
          value_name: 'Hombre',
        },
        {
          id: 'COLOR',
          name: 'Color',
          value_id: '3173321',
          value_name: 'Cobalt blue',
        },
        {
          id: 'FABRIC_DESIGN',
          name: 'Diseño de la tela',
          value_id: '24721100',
          value_name: 'Liso',
        },
        {
          id: 'WIDTH_TYPE',
          name: 'Tipo de ancho',
          value_id: '15665144',
          value_name: 'Estándar',
        },
        {
          id: 'SIZE_GRID_ROW_ID',
          name: 'ID de la fila de la guía de talles',
          value_id: '45105336',
          value_name: '2516266:15',
        },
        {
          id: 'MAIN_COLOR',
          name: 'Color principal',
          value_id: '2450293',
          value_name: 'Azul',
        },
        {
          id: 'SIZE_GRID_ID',
          name: 'ID de la guía de talles',
          value_id: '45028923',
          value_name: '2516266',
        },
        {
          id: 'EXTERIOR_MATERIALS',
          name: 'Materiales del exterior',
          value_name: 'Sintético',
        },
        {
          id: 'INTERIOR_MATERIALS',
          name: 'Materiales del interior',
          value_name: 'Tela',
        },
        {
          id: 'OUTSOLE_MATERIALS',
          name: 'Materiales de la suela',
          value_name: 'Plástico',
        },
        {
          id: 'FOOTWEAR_TYPE',
          name: 'Tipo de calzado',
          value_id: '517583',
          value_name: 'Zapatilla',
        },
        {
          id: 'ADJUSTMENT_TYPES',
          name: 'Tipos de ajuste',
          value_name: 'Cordones',
        },
        {
          id: 'WITH_RECYCLED_MATERIALS',
          name: 'Con materiales reciclados',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'RECOMMENDED_USES',
          name: 'Usos recomendados',
          value_name: 'Running',
        },
        {
          id: 'IS_IMPERMEABLE',
          name: 'Es impermeable',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_ANTI_SLIP_OUTSOLE',
          name: 'Con suela antideslizante',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PLATFORM',
          name: 'Con plataforma',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_REMOVABLE_INSOLES',
          name: 'Con plantillas removibles',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_BREATHEABLE_INSOLES',
          name: 'Con plantillas transpirables',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'INSOLES_MATERIALS',
          name: 'Materiales de las plantillas',
          value_name: 'Espuma',
        },
        {
          id: 'SHAFT_TYPE',
          name: 'Tipo de caña',
          value_id: '1164226',
          value_name: 'Baja',
        },
        {
          id: 'MIDSOLE_MATERIALS',
          name: 'Materiales de la mediasuela',
          value_name: 'Goma EVA',
        },
        {
          id: 'WITH_PADDED_MIDSOLE',
          name: 'Con mediasuela acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_TONGUE',
          name: 'Con lengüeta acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_COLLAR',
          name: 'Con cuello acolchado',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'SUITABLE_SURFACES',
          name: 'Superficies aptas',
          value_name: 'Cemento',
        },
        {
          id: 'RELEASE_SEASON',
          name: 'Temporada de lanzamiento',
          value_id: '994284',
          value_name: 'Otoño/Invierno',
        },
        {
          id: 'RELEASE_YEAR',
          name: 'Año de lanzamiento',
          value_id: '22764580',
          value_name: '2024',
        },
        {
          id: 'SIZE',
          name: 'Talle',
          value_name: '43 AR',
        },
      ],
      pictures: [
        {
          id: '664561-MLA82398344712_022025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_664561-MLA82398344712_022025-F.jpg',
        },
        {
          id: '955902-MLA82398344728_022025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_955902-MLA82398344728_022025-F.jpg',
        },
        {
          id: '711389-MLA82683304033_022025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_711389-MLA82683304033_022025-F.jpg',
        },
        {
          id: '659722-MLA82398260638_022025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_659722-MLA82398260638_022025-F.jpg',
        },
        {
          id: '738332-MLA82683439247_022025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_738332-MLA82683439247_022025-F.jpg',
        },
        {
          id: '707563-MLA82398344776_022025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_707563-MLA82398344776_022025-F.jpg',
        },
        {
          id: '975142-MLA82398260648_022025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_975142-MLA82398260648_022025-F.jpg',
        },
        {
          id: '907389-MLA82398260666_022025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_907389-MLA82398260666_022025-F.jpg',
        },
      ],
      status: 'active',
      catalog_product_id: 'MLA46411446',
      pdp_types: [],
      domain_id: 'MLA-SNEAKERS',
      settings: {
        listing_strategy: 'open',
        exclusive: false,
      },
      main_features: [],
      children_ids: [],
      quality_type: 'COMPLETE',
      priority: 'MEDIUM',
      type: 'PRODUCT',
      site_id: 'MLA',
      variations: [],
      parent_id: 'MLA45582926',
    },
    {
      id: 'MLA47726630',
      name: 'Zapatillas Response Ih6088 adidas',
      description: '',
      date_created: '2025-04-06T01:44:06Z',
      keywords: 'Zapatillas Response Ih6088 adidas',
      attributes: [
        {
          id: 'BRAND',
          name: 'Marca',
          value_id: '14810',
          value_name: 'adidas',
        },
        {
          id: 'MODEL',
          name: 'Modelo',
          value_id: '472835',
          value_name: 'Response',
        },
        {
          id: 'GENDER',
          name: 'Género',
          value_id: '339665',
          value_name: 'Mujer',
        },
        {
          id: 'ALPHANUMERIC_MODEL',
          name: 'Modelo alfanumérico',
          value_id: '46992433',
          value_name: 'IH6088',
        },
        {
          id: 'COLOR',
          name: 'Color',
          value_id: '52049',
          value_name: 'Negro',
        },
        {
          id: 'FABRIC_DESIGN',
          name: 'Diseño de la tela',
          value_id: '24721100',
          value_name: 'Liso',
        },
        {
          id: 'WIDTH_TYPE',
          name: 'Tipo de ancho',
          value_id: '44710799',
          value_name: 'Ajuste clásico',
        },
        {
          id: 'SIZE_GRID_ROW_ID',
          name: 'ID de la fila de la guía de talles',
          value_id: '11505405',
          value_name: '210010:2',
        },
        {
          id: 'SIZE_GRID_ID',
          name: 'ID de la guía de talles',
          value_id: '11505053',
          value_name: '210010',
        },
        {
          id: 'EXTERIOR_MATERIALS',
          name: 'Materiales del exterior',
          value_name: 'Tela',
        },
        {
          id: 'INTERIOR_MATERIALS',
          name: 'Materiales del interior',
          value_name: 'Tela',
        },
        {
          id: 'OUTSOLE_MATERIALS',
          name: 'Materiales de la suela',
          value_name: 'Sintético',
        },
        {
          id: 'FOOTWEAR_TYPE',
          name: 'Tipo de calzado',
          value_id: '517583',
          value_name: 'Zapatilla',
        },
        {
          id: 'ADJUSTMENT_TYPES',
          name: 'Tipos de ajuste',
          value_name: 'Cordones',
        },
        {
          id: 'WITH_RECYCLED_MATERIALS',
          name: 'Con materiales reciclados',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'RECOMMENDED_USES',
          name: 'Usos recomendados',
          value_name: 'Deportivo',
        },
        {
          id: 'IS_IMPERMEABLE',
          name: 'Es impermeable',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_ANTI_SLIP_OUTSOLE',
          name: 'Con suela antideslizante',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PLATFORM',
          name: 'Con plataforma',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_REMOVABLE_INSOLES',
          name: 'Con plantillas removibles',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_BREATHEABLE_INSOLES',
          name: 'Con plantillas transpirables',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'INSOLES_MATERIALS',
          name: 'Materiales de las plantillas',
          value_name: 'Espuma',
        },
        {
          id: 'SHAFT_TYPE',
          name: 'Tipo de caña',
          value_id: '1164226',
          value_name: 'Baja',
        },
        {
          id: 'MIDSOLE_MATERIALS',
          name: 'Materiales de la mediasuela',
          value_name: 'Goma EVA',
        },
        {
          id: 'WITH_PADDED_MIDSOLE',
          name: 'Con mediasuela acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_TONGUE',
          name: 'Con lengüeta acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_COLLAR',
          name: 'Con cuello acolchado',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'SUITABLE_SURFACES',
          name: 'Superficies aptas',
          value_name: 'Cemento',
        },
        {
          id: 'RELEASE_SEASON',
          name: 'Temporada de lanzamiento',
          value_id: '994284',
          value_name: 'Otoño/Invierno',
        },
        {
          id: 'RELEASE_YEAR',
          name: 'Año de lanzamiento',
          value_id: '7885601',
          value_name: '2020',
        },
        {
          id: 'SIZE',
          name: 'Talle',
          value_id: '11375686',
          value_name: '34.5 AR',
        },
      ],
      pictures: [
        {
          id: '895416-MLA83272780368_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_895416-MLA83272780368_042025-F.jpg',
        },
        {
          id: '927405-MLA83564399937_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_927405-MLA83564399937_042025-F.jpg',
        },
        {
          id: '769103-MLA83272957274_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_769103-MLA83272957274_042025-F.jpg',
        },
        {
          id: '810654-MLA83272760870_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_810654-MLA83272760870_042025-F.jpg',
        },
        {
          id: '990241-MLA83272780376_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_990241-MLA83272780376_042025-F.jpg',
        },
        {
          id: '941665-MLA83564399945_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_941665-MLA83564399945_042025-F.jpg',
        },
        {
          id: '774925-MLA83564174071_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_774925-MLA83564174071_042025-F.jpg',
        },
        {
          id: '777970-MLA83272760874_042025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_777970-MLA83272760874_042025-F.jpg',
        },
      ],
      status: 'active',
      catalog_product_id: 'MLA47726630',
      pdp_types: [],
      domain_id: 'MLA-SNEAKERS',
      settings: {
        listing_strategy: 'open',
        exclusive: false,
      },
      main_features: [],
      children_ids: [],
      quality_type: 'COMPLETE',
      priority: 'MEDIUM',
      type: 'PRODUCT',
      site_id: 'MLA',
      variations: [],
      parent_id: 'MLA45825186',
    },
    {
      id: 'MLA44528016',
      name: 'Zapatillas Response Ig1416 adidas',
      description: '',
      date_created: '2024-12-05T23:30:08Z',
      keywords: 'Zapatillas Response Ig1416 adidas',
      attributes: [
        {
          id: 'BRAND',
          name: 'Marca',
          value_id: '14810',
          value_name: 'adidas',
        },
        {
          id: 'MODEL',
          name: 'Modelo',
          value_id: '45645987',
          value_name: 'Response MAU78',
        },
        {
          id: 'GENDER',
          name: 'Género',
          value_id: '339666',
          value_name: 'Hombre',
        },
        {
          id: 'COLOR',
          name: 'Color',
          value_id: '283165',
          value_name: 'Gris',
        },
        {
          id: 'FABRIC_DESIGN',
          name: 'Diseño de la tela',
          value_id: '24721100',
          value_name: 'Liso',
        },
        {
          id: 'WIDTH_TYPE',
          name: 'Tipo de ancho',
          value_id: '44710799',
          value_name: 'Ajuste clásico',
        },
        {
          id: 'SIZE_GRID_ROW_ID',
          name: 'ID de la fila de la guía de talles',
          value_id: '45656096',
          value_name: '2632143:25',
        },
        {
          id: 'SIZE_GRID_ID',
          name: 'ID de la guía de talles',
          value_id: '45646001',
          value_name: '2632143',
        },
        {
          id: 'EXTERIOR_MATERIALS',
          name: 'Materiales del exterior',
          value_name: 'Tela',
        },
        {
          id: 'INTERIOR_MATERIALS',
          name: 'Materiales del interior',
          value_name: 'Tela',
        },
        {
          id: 'OUTSOLE_MATERIALS',
          name: 'Materiales de la suela',
          value_name: 'Sintético',
        },
        {
          id: 'FOOTWEAR_TYPE',
          name: 'Tipo de calzado',
          value_id: '517583',
          value_name: 'Zapatilla',
        },
        {
          id: 'ADJUSTMENT_TYPES',
          name: 'Tipos de ajuste',
          value_name: 'Cordones',
        },
        {
          id: 'WITH_RECYCLED_MATERIALS',
          name: 'Con materiales reciclados',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'RECOMMENDED_USES',
          name: 'Usos recomendados',
          value_name: 'Deportivo',
        },
        {
          id: 'IS_IMPERMEABLE',
          name: 'Es impermeable',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_ANTI_SLIP_OUTSOLE',
          name: 'Con suela antideslizante',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PLATFORM',
          name: 'Con plataforma',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_LIGHTS',
          name: 'Con luces',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_REMOVABLE_INSOLES',
          name: 'Con plantillas removibles',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_BREATHEABLE_INSOLES',
          name: 'Con plantillas transpirables',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'INSOLES_MATERIALS',
          name: 'Materiales de las plantillas',
          value_name: 'Espuma',
        },
        {
          id: 'SHAFT_TYPE',
          name: 'Tipo de caña',
          value_id: '1164226',
          value_name: 'Baja',
        },
        {
          id: 'MIDSOLE_MATERIALS',
          name: 'Materiales de la mediasuela',
          value_name: 'Goma EVA',
        },
        {
          id: 'WITH_PADDED_MIDSOLE',
          name: 'Con mediasuela acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_TONGUE',
          name: 'Con lengüeta acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_COLLAR',
          name: 'Con cuello acolchado',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'SUITABLE_SURFACES',
          name: 'Superficies aptas',
          value_name: 'Cemento',
        },
        {
          id: 'RELEASE_SEASON',
          name: 'Temporada de lanzamiento',
          value_id: '994283',
          value_name: 'Primavera/Verano',
        },
        {
          id: 'RELEASE_YEAR',
          name: 'Año de lanzamiento',
          value_id: '22764580',
          value_name: '2024',
        },
        {
          id: 'SIZE',
          name: 'Talle',
          value_name: '49 AR',
        },
      ],
      pictures: [
        {
          id: '958562-MLA80927523386_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_958562-MLA80927523386_122024-F.jpg',
        },
        {
          id: '990419-MLA81193998641_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_990419-MLA81193998641_122024-F.jpg',
        },
        {
          id: '889566-MLA80927523392_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_889566-MLA80927523392_122024-F.jpg',
        },
        {
          id: '732839-MLA80927667290_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_732839-MLA80927667290_122024-F.jpg',
        },
        {
          id: '907751-MLA80927705362_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_907751-MLA80927705362_122024-F.jpg',
        },
        {
          id: '957700-MLA80927705370_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_957700-MLA80927705370_122024-F.jpg',
        },
        {
          id: '661095-MLA81193892837_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_661095-MLA81193892837_122024-F.jpg',
        },
        {
          id: '762185-MLA80927667324_122024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_762185-MLA80927667324_122024-F.jpg',
        },
      ],
      status: 'active',
      catalog_product_id: 'MLA44528016',
      pdp_types: [],
      domain_id: 'MLA-SNEAKERS',
      settings: {
        listing_strategy: 'open',
        exclusive: false,
      },
      main_features: [],
      children_ids: [],
      quality_type: 'COMPLETE',
      priority: 'MEDIUM',
      type: 'PRODUCT',
      site_id: 'MLA',
      variations: [],
      parent_id: 'MLA44518383',
    },
    {
      id: 'MLA44048525',
      name: 'Zapatillas Rapidmove If3204 adidas',
      description: '',
      date_created: '2024-11-28T16:53:39Z',
      keywords: 'Zapatillas Rapidmove If3204 adidas',
      attributes: [
        {
          id: 'BRAND',
          name: 'Marca',
          value_id: '14810',
          value_name: 'adidas',
        },
        {
          id: 'MODEL',
          name: 'Modelo',
          value_id: '45026442',
          value_name: 'Rapidmove LYP70',
        },
        {
          id: 'GENDER',
          name: 'Género',
          value_id: '339665',
          value_name: 'Mujer',
        },
        {
          id: 'COLOR',
          name: 'Color',
          value_id: '52055',
          value_name: 'Blanco',
        },
        {
          id: 'FABRIC_DESIGN',
          name: 'Diseño de la tela',
          value_id: '24721100',
          value_name: 'Liso',
        },
        {
          id: 'WIDTH_TYPE',
          name: 'Tipo de ancho',
          value_id: '44710799',
          value_name: 'Ajuste clásico',
        },
        {
          id: 'SIZE_GRID_ROW_ID',
          name: 'ID de la fila de la guía de talles',
          value_id: '45144180',
          value_name: '2597275:17',
        },
        {
          id: 'SIZE_GRID_ID',
          name: 'ID de la guía de talles',
          value_id: '45026444',
          value_name: '2597275',
        },
        {
          id: 'EXTERIOR_MATERIALS',
          name: 'Materiales del exterior',
          value_name: 'Tela',
        },
        {
          id: 'INTERIOR_MATERIALS',
          name: 'Materiales del interior',
          value_name: 'Tela',
        },
        {
          id: 'OUTSOLE_MATERIALS',
          name: 'Materiales de la suela',
          value_name: 'Sintético',
        },
        {
          id: 'FOOTWEAR_TYPE',
          name: 'Tipo de calzado',
          value_id: '517583',
          value_name: 'Zapatilla',
        },
        {
          id: 'ADJUSTMENT_TYPES',
          name: 'Tipos de ajuste',
          value_name: 'Cordones',
        },
        {
          id: 'WITH_RECYCLED_MATERIALS',
          name: 'Con materiales reciclados',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'RECOMMENDED_USES',
          name: 'Usos recomendados',
          value_name: 'Deportivo',
        },
        {
          id: 'IS_IMPERMEABLE',
          name: 'Es impermeable',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_ANTI_SLIP_OUTSOLE',
          name: 'Con suela antideslizante',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PLATFORM',
          name: 'Con plataforma',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_LIGHTS',
          name: 'Con luces',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_REMOVABLE_INSOLES',
          name: 'Con plantillas removibles',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_BREATHEABLE_INSOLES',
          name: 'Con plantillas transpirables',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'INSOLES_MATERIALS',
          name: 'Materiales de las plantillas',
          value_name: 'Espuma',
        },
        {
          id: 'SHAFT_TYPE',
          name: 'Tipo de caña',
          value_id: '1164226',
          value_name: 'Baja',
        },
        {
          id: 'MIDSOLE_MATERIALS',
          name: 'Materiales de la mediasuela',
          value_name: 'Goma EVA',
        },
        {
          id: 'WITH_PADDED_MIDSOLE',
          name: 'Con mediasuela acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_TONGUE',
          name: 'Con lengüeta acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_COLLAR',
          name: 'Con cuello acolchado',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'SUITABLE_SURFACES',
          name: 'Superficies aptas',
          value_name: 'Cemento',
        },
        {
          id: 'RELEASE_SEASON',
          name: 'Temporada de lanzamiento',
          value_id: '994283',
          value_name: 'Primavera/Verano',
        },
        {
          id: 'RELEASE_YEAR',
          name: 'Año de lanzamiento',
          value_id: '22764580',
          value_name: '2024',
        },
        {
          id: 'SIZE',
          name: 'Talle',
          value_name: '44 AR',
        },
      ],
      pictures: [
        {
          id: '782085-MLA80990803883_112024',
          url: 'https://http2.mlstatic.com/D_NQ_NP_782085-MLA80990803883_112024-F.jpg',
        },
      ],
      status: 'active',
      catalog_product_id: 'MLA44048525',
      pdp_types: [],
      domain_id: 'MLA-SNEAKERS',
      settings: {
        listing_strategy: 'open',
        exclusive: false,
      },
      main_features: [],
      children_ids: [],
      quality_type: 'COMPLETE',
      priority: 'MEDIUM',
      type: 'PRODUCT',
      site_id: 'MLA',
      variations: [],
      parent_id: 'MLA43941602',
    },
    {
      id: 'MLA45630772',
      name: 'Zapatillas Response Ih6092 adidas',
      description: '',
      date_created: '2025-01-22T04:49:48Z',
      keywords: 'Zapatillas Response Ih6092 adidas',
      attributes: [
        {
          id: 'BRAND',
          name: 'Marca',
          value_id: '14810',
          value_name: 'adidas',
        },
        {
          id: 'MODEL',
          name: 'Modelo',
          value_id: '472835',
          value_name: 'Response',
        },
        {
          id: 'GENDER',
          name: 'Género',
          value_id: '339666',
          value_name: 'Hombre',
        },
        {
          id: 'COLOR',
          name: 'Color',
          value_id: '283165',
          value_name: 'Gris',
        },
        {
          id: 'FABRIC_DESIGN',
          name: 'Diseño de la tela',
          value_id: '24721100',
          value_name: 'Liso',
        },
        {
          id: 'WIDTH_TYPE',
          name: 'Tipo de ancho',
          value_id: '44710799',
          value_name: 'Ajuste clásico',
        },
        {
          id: 'SIZE_GRID_ROW_ID',
          name: 'ID de la fila de la guía de talles',
          value_id: '45116804',
          value_name: '2516266:9',
        },
        {
          id: 'MAIN_COLOR',
          name: 'Color principal',
          value_id: '2450294',
          value_name: 'Gris',
        },
        {
          id: 'SIZE_GRID_ID',
          name: 'ID de la guía de talles',
          value_id: '45028923',
          value_name: '2516266',
        },
        {
          id: 'EXTERIOR_MATERIALS',
          name: 'Materiales del exterior',
          value_name: 'Tela',
        },
        {
          id: 'INTERIOR_MATERIALS',
          name: 'Materiales del interior',
          value_name: 'Tela',
        },
        {
          id: 'OUTSOLE_MATERIALS',
          name: 'Materiales de la suela',
          value_name: 'Sintético',
        },
        {
          id: 'FOOTWEAR_TYPE',
          name: 'Tipo de calzado',
          value_id: '517583',
          value_name: 'Zapatilla',
        },
        {
          id: 'ADJUSTMENT_TYPES',
          name: 'Tipos de ajuste',
          value_name: 'Cordones',
        },
        {
          id: 'WITH_RECYCLED_MATERIALS',
          name: 'Con materiales reciclados',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'RECOMMENDED_USES',
          name: 'Usos recomendados',
          value_name: 'Deportivo',
        },
        {
          id: 'IS_IMPERMEABLE',
          name: 'Es impermeable',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_ANTI_SLIP_OUTSOLE',
          name: 'Con suela antideslizante',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PLATFORM',
          name: 'Con plataforma',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_LIGHTS',
          name: 'Con luces',
          value_id: '242084',
          value_name: 'No',
        },
        {
          id: 'WITH_REMOVABLE_INSOLES',
          name: 'Con plantillas removibles',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_BREATHEABLE_INSOLES',
          name: 'Con plantillas transpirables',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'INSOLES_MATERIALS',
          name: 'Materiales de las plantillas',
          value_name: 'Espuma',
        },
        {
          id: 'SHAFT_TYPE',
          name: 'Tipo de caña',
          value_id: '1164226',
          value_name: 'Baja',
        },
        {
          id: 'MIDSOLE_MATERIALS',
          name: 'Materiales de la mediasuela',
          value_name: 'Goma EVA',
        },
        {
          id: 'WITH_PADDED_MIDSOLE',
          name: 'Con mediasuela acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_TONGUE',
          name: 'Con lengüeta acolchada',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'WITH_PADDED_COLLAR',
          name: 'Con cuello acolchado',
          value_id: '242085',
          value_name: 'Sí',
        },
        {
          id: 'SUITABLE_SURFACES',
          name: 'Superficies aptas',
          value_name: 'Cemento',
        },
        {
          id: 'RELEASE_SEASON',
          name: 'Temporada de lanzamiento',
          value_id: '994284',
          value_name: 'Otoño/Invierno',
        },
        {
          id: 'RELEASE_YEAR',
          name: 'Año de lanzamiento',
          value_id: '22764580',
          value_name: '2024',
        },
        {
          id: 'SIZE',
          name: 'Talle',
          value_name: '39 AR',
        },
      ],
      pictures: [
        {
          id: '894195-MLA81779745192_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_894195-MLA81779745192_012025-F.jpg',
        },
        {
          id: '806905-MLA82058193639_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_806905-MLA82058193639_012025-F.jpg',
        },
        {
          id: '847720-MLA82058193643_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_847720-MLA82058193643_012025-F.jpg',
        },
        {
          id: '622735-MLA82058193651_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_622735-MLA82058193651_012025-F.jpg',
        },
        {
          id: '917003-MLA81779735656_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_917003-MLA81779735656_012025-F.jpg',
        },
        {
          id: '631707-MLA81779755058_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_631707-MLA81779755058_012025-F.jpg',
        },
        {
          id: '786846-MLA82058389625_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_786846-MLA82058389625_012025-F.jpg',
        },
        {
          id: '867567-MLA81779755072_012025',
          url: 'https://http2.mlstatic.com/D_NQ_NP_867567-MLA81779755072_012025-F.jpg',
        },
      ],
      status: 'active',
      catalog_product_id: 'MLA45630772',
      pdp_types: [],
      domain_id: 'MLA-SNEAKERS',
      settings: {
        listing_strategy: 'open',
        exclusive: false,
      },
      main_features: [],
      children_ids: [],
      quality_type: 'COMPLETE',
      priority: 'MEDIUM',
      type: 'PRODUCT',
      site_id: 'MLA',
      variations: [],
      parent_id: 'MLA45582926',
    },
  ],
  used_attributes: [
    {
      id: 'BRAND',
      name: 'Marca',
      value_id: '14810',
      value_name: 'adidas',
    },
    {
      id: 'FOOTWEAR_TYPE',
      name: 'Tipo de calzado',
      value_id: '517583',
      value_name: 'Zapatilla',
    },
    {
      id: 'ADJUSTMENT_TYPES',
      name: 'Tipos de ajuste',
      value_name: 'Cordones',
    },
    {
      id: 'IS_IMPERMEABLE',
      name: 'Es impermeable',
      value_id: '242084',
      value_name: 'No',
    },
    {
      id: 'WITH_ANTI_SLIP_OUTSOLE',
      name: 'Con suela antideslizante',
      value_id: '242085',
      value_name: 'Sí',
    },
    {
      id: 'WITH_PLATFORM',
      name: 'Con plataforma',
      value_id: '242084',
      value_name: 'No',
    },
    {
      id: 'SHAFT_TYPE',
      name: 'Tipo de caña',
      value_id: '1164226',
      value_name: 'Baja',
    },
    {
      id: 'WITH_PADDED_MIDSOLE',
      name: 'Con mediasuela acolchada',
      value_id: '242085',
      value_name: 'Sí',
    },
    {
      id: 'WITH_PADDED_TONGUE',
      name: 'Con lengüeta acolchada',
      value_id: '242085',
      value_name: 'Sí',
    },
    {
      id: 'WITH_PADDED_COLLAR',
      name: 'Con cuello acolchado',
      value_id: '242085',
      value_name: 'Sí',
    },
  ],
  query_type: 'PRODUCT_NAME',
};
